### ISSUE TITLE
테스트 이슈

### ISSUE THREAD

**Issue by CHOEJANGHYEOK** [swsnu/swpp2020-team4#98]
테스트 중 문제가 있었던 부분을 알려주세요

**Comment by mushypeas** [comment]
- 사용환경: 윈도우10, 크롬
![캡처](https://user-images.githubusercontent.com/43646919/101761727-d8aa5a80-3b1f-11eb-8bbd-7c170cfab4c9.PNG)
글씨가 서로 겹칩니다

**Comment by yg-moon** [comment]
![team4](https://user-images.githubusercontent.com/56223439/101761733-d9db8780-3b1f-11eb-81cf-18f598f6380c.png)

대문의 띄어쓰기가 의도치 않게 되는 부분이 있는 것 같고, Get Started 버튼을 눌러도 아무 일도 일어나지 않습니다.

**Comment by sdm1230** [comment]
<img width="494" alt="스크린샷 2020-12-10 오후 7 42 45" src="https://user-images.githubusercontent.com/47305937/101761757-e19b2c00-3b1f-11eb-98bb-ab5dc1cf6ef5.png">
글씨가 좀 망가져있습니다..!

**Comment by robotronic0694** [comment]
![image](https://user-images.githubusercontent.com/44860976/101761864-0394ae80-3b20-11eb-8226-11960e4fbb8a.png)
메인 페이지에서 넘어갈 수가 없습니다...

**Comment by ariadne240** [comment]
Mac OS, Chrome인데 저도 위처럼 글씨가 띄어져 있습니다.

**Comment by jsgh7276** [comment]
로그인이 혹시 되나요? 저는 안되는 것 같습니다.

**Comment by yankee624** [comment]
저도 sign up이 안돼서 진행이 안되고 있습니다

**Comment by jongtaeklho** [comment]
저도 로그인이 안됩니다

**Comment by sdm1230** [comment]
사인업/ 로그인하는데 아무 반응이 없어서 잘 되는지 모르겠습니다. 일단 다 실패한 것 같습니다

**Comment by ariadne240** [comment]
Get started 눌러도 아무 일도 일어나지 않는 것 같습니다.

**Comment by sdm1230** [comment]
> 사인업/ 로그인하는데 아무 반응이 없어서 잘 되는지 모르겠습니다. 일단 다 실패한 것 같습니다

아 기다리니 alert 가 왔습니다..!

**Comment by ChanwooLucioLee** [comment]
저도 sign up이 안 됩니다.

**Comment by sugsugsug** [comment]
서버문제인지는 모르겠지만 signup을 해도??login이 되지 않는 것 같습니다
혹시 공용 아이디를 알려주실 수 있을까요?

**Comment by promet99** [comment]
넵 지금 몇몇분들께서 알고리즘 테스트를 여러개 돌리셔서 백엔드에 부하가 많이 간 것 같습니다

**Comment by creeper00** [comment]
로그인이 잘 안되는 거 같습니다 ㅠㅠ

**Comment by promet99** [comment]
알고리즘 테스트를 한번에 여러 개씩 돌리지는 않아 주셨으면 좋겠습니다.
부하 테스트까지는 하지 않아주셨으면 좋겠습니다 ㅠㅠ

**Comment by juimdpp** [comment]
사인업이 잘 안 되는것 같습니다....

**Comment by ariadne240** [comment]
사인업이 잘 안 됩니다.

**Comment by promet99** [comment]
주식 테스트를 한번에 여러개 돌리다보니 장고가 좀 얼은 것 같아요. ㅠㅠ
상당히 많은 테스트를 처음 동시에 돌려서 이렇게 된 것 같습니다.
조금만 기다려 주시면 감사하겠습니다

**Comment by magnolia93** [comment]
username에 test59243744 와 같이 임의로 작성해서 가입을 하려고 했는데 username already exists라는 alert가 뜹니다

**Comment by promet99** [comment]
> 
> 
> username에 test59243744 와 같이 임의로 작성해서 가입을 하려고 했는데 username already exists라는 alert가 뜹니다

네, 서버 응답이 없으면 저렇게 뜨기도 합니다

**Comment by yg-moon** [comment]
어떤 username으로 가입하든 username already exists 라는 alert가 발생하는 것 같습니다.

**Comment by gina7484** [comment]
접속자가 많아서 sign up, sign in 은 못했지만 leaderboard는 들어가져서 가봤는데
로그인을 안해도 들어가지네요.
혹시 로그인하지 않은 유저들에게도 leaderboard를 제공하나요?
사소한 부분이긴 하지만 만약 그렇다면 로그인한 유저와 그렇지 않은 유저에게 보여지는 leaderboard 정보를 다르게 하면 좋을 것 같습니다.

**Comment by hiddenpunch** [comment]
leaderboard만 리다이렉트 되었습니다.

**Comment by promet99** [comment]
넵 리더보드는 모두가 볼 수 있게 하였습니다. 오늘 발생한 백엔드 서버 부하 문제는 다시 고치도록 하겠습니다.
리뷰 해주신 분들 모두 감사드립니다
